kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: idaasdb
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - mariadb
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'mariadb:10.2'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/openshift/mariadb:10.2
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    name: idaasdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: idaasdb
    spec:
      volumes:
        - name: idaasdb-svc-data
          persistentVolumeClaim:
            claimName: idaasdb-svc
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                  -D $MYSQL_DATABASE -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: mariadb
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: idaasdb-svc
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idaasdb-svc
                  key: database-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idaasdb-svc
                  key: database-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: idaasdb-svc
                  key: database-name
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: idaasdb-svc-data
              mountPath: /var/lib/mysql/data
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/mariadb:10.2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
--- 
kind: Secret
apiVersion: v1
metadata:
  name: idaasdb-svc
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: aWRhYXNkYg==
  database-password: cndSSG1HSjh0dk9OSWxKWQ==
  database-root-password: OE9INlVSRkJDeW1UWEJWYw==
  database-user: aWRhYXM=
type: Opaque

---   
kind: Service
apiVersion: v1
metadata:
  name: idaas-dbsvc
  annotations:
    template.openshift.io/expose-uri: 'mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}'
spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    name: idaas-dbsvc
---  

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: idaasdb-svc
  finalizers:
    - kubernetes.io/pvc-protection  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

--- 

kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/display-name: MariaDB
  name: mariadb
  namespace: openshift
  labels:
    samples.operator.openshift.io/managed: 'true'
spec:
  lookupPolicy:
    local: false
  tags:
    - name: '10.2'
      annotations:
        description: >-
          Provides a MariaDB 10.2 database on RHEL 7. For more information about
          using this database image, including OpenShift considerations, see
          https://github.com/sclorg/mariadb-container/tree/master/10.2/README.md.
        iconClass: icon-mariadb
        openshift.io/display-name: MariaDB 10.2
        openshift.io/provider-display-name: 'Red Hat, Inc.'
        tags: 'database,mariadb'
        version: '10.2'
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhscl/mariadb-102-rhel7:latest'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local

