apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: idaas-db
    component: mysql
spec:
  ports:
    - name: dbapi
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: idaas-db
    component: mysql
