apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-echo
spec:
  results:
    - name: builtImage-digest
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  resources:
    inputs:
      - name: idaas-source
        type: git
    outputs:
      - name: idaas-image
        type: image
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: shared-workspace        
  steps:
    - name: echo
      image: busybox
      script: |
        #!/bin/sh
        set -xe
        echo shared-workspace-path: $(workspaces.shared-workspace.path)
        echo idaas-image: $(resources.outputs.idaas-image.url)
        echo pwd:  $(pwd)
        ls -l      

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-mvnpackage
spec:
  results:
    - name: builtImage-digest
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  resources:
    inputs:
      - name: idaas-source
        type: git
    outputs:
      - name: idaas-image
        type: image
    taskRef:
      name: maven
      kind: ClusterTask
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: shared-workspace
