apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-echo
spec:
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  workspaces:
    - name: shared-repo
    - name: maven-settings
    - name: source
  resources:
    outputs:
      - name: idaas-image
        type: image
  steps:
    - name: echo
      image: busybox
      script: |
        #!/bin/sh
        set -xe
        echo shared-repo-path: $(workspaces.shared-repo.path)
        echo idaas-source-url :$(params.repo-url)
        echo idaas-image: $(resources.outputs.idaas-image.url)
        echo pwd:  $(pwd)
        ls -lah      
      

# ---

# apiVersion: tekton.dev/v1beta1
# kind: Task
# metadata:
#   name: build-mvnpackage
# spec:
#   results:
#     - name: builtImage-digest
#   workspaces:
#     - name: shared-workspace
#     - name: maven-settings
#   resources:
#     inputs:
#       - name: idaas-source
#         type: git
#     outputs:
#       - name: idaas-image
#         type: image
#     taskRef:
#       name: maven
#       kind: ClusterTask
#     workspaces:
#       - name: maven-settings
#         workspace: maven-settings
#       - name: source
#         workspace: shared-workspace
