apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: idaas-testingcomponent-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: idaas-app-build
    workspaces:
      - name: shared-workspace
        workspace: shared-workspace
      - name: maven-settings
        workspace: maven-settings
    taskRef:
        name: idaas-app-build
        resources:
        inputs:
          - name: idaas-source
            resource: app-git
        outputs:
          - name: idaas-image
            resource: app-image
          
