apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: idaas-testingcomponent-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build-s2i
    taskRef:
      name: s2i-java-8
      kind: ClusterTask
    params:
      - name: TLSVERIFY
        value: "false"
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image 