apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: idaas-testingcomponent-pipeline
spec:
  workspaces:
      - name: shared-repo
      - name: maven-settings
      - name: shared-ws
  params:
  - name: idaas-repo-url
    type: string
    description: The git repository URL to clone from.      
  resources:
  - name: app-image
    type: image
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-ws
    params:
    - name: url
      value: $(params.idaas-repo-url)
    - name: deleteExisting
      value: "true"
  - name: build-echo
    taskRef: 
      name: build-echo
    resources:
      outputs:
      - name: idaas-image
        resource: app-image
    runAfter: 
      - fetch-repo
    workspaces:
      - name: shared-repo
        workspace: shared-repo
      - name: maven-settings
        workspace: maven-settings    
      - name: source
        workspace: shared-ws 
    params:
    - name: repo-url
      value: $(params.idaas-repo-url)        
  - name: package
    resources:
    taskRef:
      name: maven
    runAfter:
      - build-echo
    workspaces:
      - name: maven-repo
        workspace: shared-repo
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: shared-ws
  - name: generate-image-push
    resources:
      outputs:
      - name: image
        resource:  app-image
    taskRef:
      name: bud-push
    runAfter:
      - package
    workspaces:
      - name: source
        workspace: shared-ws      

